/* SPDX-License-Identifier: GPL-3.0-or-later */
#ifndef WIFICAPC_OUI_H
#define WIFICAPC_OUI_H

#include <stdint.h>

/*
 * OUI → vendor lookup, backed by an embedded IEEE MA-L table
 * (see src/oui_table.h, generated by tools/gen_oui.py).
 *
 * Returns a static, NUL-terminated vendor string for the MAC's 24-bit OUI,
 * or NULL when:
 *   - the OUI is not in the registry, or
 *   - the MAC is locally-administered (the U/L bit is set — i.e. a
 *     randomized/private client address), where the OUI is meaningless, or
 *   - the MAC is group/multicast-addressed.
 * The returned pointer is valid for the lifetime of the process; do not free.
 */
const char *oui_lookup(const uint8_t mac[6]);

#endif
