#!/usr/bin/env python3
"""Generate src/oui_table.h from IEEE oui.csv (MA-L, 24-bit OUIs).
Vendor strings are cleaned, truncated, and de-duplicated into a pool."""
import csv, sys, re

MAXV = 31  # fits TABLE_VENDOR_MAX(32) - 1
def clean(name):
    n = " ".join(name.split())            # collapse whitespace
    # trim common corporate suffixes for compactness/readability
    n = re.sub(r',?\s+(Inc\.?|Ltd\.?|LLC|Co\.,?\s*Ltd\.?|Corporation|Corp\.?|GmbH|S\.A\.|Pty\.?\s*Ltd\.?|Technologies|Technology|Electronics)\b\.?$', '', n, flags=re.I).strip()
    n = n.strip(' ,.')
    if len(n) > MAXV:
        n = n[:MAXV].rstrip()
    return n

rows = []
with open(sys.argv[1], newline='', encoding='utf-8', errors='replace') as f:
    r = csv.reader(f)
    next(r, None)
    for row in r:
        if len(row) < 3 or row[0] != 'MA-L':
            continue
        try:
            oui = int(row[1], 16)
        except ValueError:
            continue
        v = clean(row[2])
        if v:
            rows.append((oui, v))
rows.sort(key=lambda x: x[0])

# dedup vendor strings -> pool
pool = {}
order = []
for _, v in rows:
    if v not in pool:
        pool[v] = len(order); order.append(v)

out = ["/* Generated by tools/gen_oui.py from IEEE oui.csv — do not edit. */",
       "/* SPDX-License-Identifier: GPL-3.0-or-later */",
       "#ifndef WIFICAPC_OUI_TABLE_H", "#define WIFICAPC_OUI_TABLE_H",
       "#include <stdint.h>", ""]
out.append("static const char *const OUI_VENDORS[] = {")
for v in order:
    esc = v.replace('\\','\\\\').replace('"','\\"')
    out.append(f'\t"{esc}",')
out.append("};")
out.append(f"#define OUI_VENDORS_LEN {len(order)}")
out.append("")
vtype = "uint16_t" if len(order) <= 65535 else "uint32_t"
out.append("struct oui_entry { uint32_t oui; %s vidx; };" % vtype)
out.append("static const struct oui_entry OUI_TABLE[] = {")
for oui, v in rows:
    out.append(f"\t{{0x{oui:06x}u,{pool[v]}}},")
out.append("};")
out.append(f"#define OUI_TABLE_LEN {len(rows)}")
out.append("#endif")
open(sys.argv[2], "w").write("\n".join(out) + "\n")
print(f"entries={len(rows)} unique_vendors={len(order)} vidx={vtype}")
